### ISSUE TITLE
Adopt internal API improvements from html-webpack-plugin

### ISSUE THREAD

**Issue by bebraw** [styleguidist/mini-html-webpack-plugin#27]
More: https://dev.to/jantimon/html-webpack-plugin-4-has-been-released-125d .

Maybe it's not the worst idea to drop support for webpack 3 or less and do the API tweaks highlighted in the post.

**Comment by sapegin** [comment]
Dropping webpack 3 support is definitely a good idea! Though I don't see that slow call they mention in our plugin ;-)

**Comment by bebraw** [comment]
Let's close as we don't have the slow call anyhow.
