### ISSUE TITLE
Regression after webpack 3 compat

### ISSUE THREAD

**Issue by vxna** [styleguidist/mini-html-webpack-plugin#3]
Noticed a destructive regression for webpack 4 after https://github.com/styleguidist/mini-html-webpack-plugin/commit/e00e1dd0e01602cc46a82b4230d6c54041b0dbfc. 

No js/css assets are emitted anymore, also no errors. 
Can be reproduced with basic config, e.g. with no entry or `./src/index.js`.

**Comment by sapegin** [comment]
I guess this check should be tweaked: 

https://github.com/styleguidist/mini-html-webpack-plugin/blob/1f99098b275db9517e9229a9c00afd97bec7099a/index.js#L48

Feel free to send a PR, if you have time.
