### ISSUE TITLE
Add attributes to generateJSReferences

### ISSUE THREAD

**Issue by pldg** [styleguidist/mini-html-webpack-plugin#5]
I was trying to add some attributes in my script tag and I had to customize `generateJSReferences` function:

```js
function generateJSReferences(files = [], publicPath = '', attributes = '') {
  return files
    .map(file => `<script src="${publicPath}${file}" ${attributes}></script>`)
    .join('');
}
```

I can call it in my custom template like so: `${generateJSReferences(js, publicPath, 'defer="defer"')}`.

Would be nice to have this functionality by default in *mini-html-webpack-plugin*. What do you think? You can do the same for `generateCSSReferences`.

**Comment by sapegin** [comment]
Feel free to send a pull request. I assume it won't introduce any breaking changes?

**Comment by bebraw** [comment]
Looks like it can be a non-breaking change, yeah. Maybe it makes sense to treat `attributes` as an object that's then internally converted to attribute strings. We should do the same for both CSS and JS so it's easy to customize this portion.

**Comment by pldg** [comment]
I've forked and modified the repo: https://github.com/pldg/mini-html-webpack-plugin/blob/master/index.js

It works with custom template:

```js
new MiniHtmlWebpackPlugin({
  context: {
    title: 'Custom template',
    jsAttributes: {
      defer: 'defer',
      type: 'text/JavaScript'
    }
  },
  template: ({ css, js, title, publicPath, cssAttributes, jsAttributes }) =>
    `<!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <title>${title}</title>
          ${generateCSSReferences(css, publicPath, cssAttributes)}
        </head>
        <body>
          ${generateJSReferences(js, publicPath, jsAttributes)}
        </body>
      </html>`
})
```

Output: `<script src="main.js" defer="defer" type="text/JavaScript"></script>`

But if I tried to use it without setting up a custom template it doesn't work:

```js
new MiniHtmlWebpackPlugin({
  context: {
    title: 'Webpack demo',
    jsAttributes: {
      defer: 'defer',
      type: 'text/JavaScript'
    }
  }
})
```

Output: `<script src="main.js" ></script>`

Where am I wrong? How can I make it works with `defaultTemplate`?

**Comment by sapegin** [comment]
Would be easier to debug if you open a pull request so we can see the actual code.
